databases:
  - name: robert-garcia
    databaseName: rg_prod_db

services:
  - type: web
    name: robert-garcia
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['RENDER_DB_URL'] %>
        fromDatabase:
          name: robert-garcia
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false